### ISSUE TITLE
Dictionary styles with commas in `styles.css` file are mangled on import

### ISSUE THREAD

**Issue by stephenmk** [yomidevs/yomitan#1500]
Yomitan supports optional CSS files that may be included with importable dictionary archives. In order to prevent styles from one dictionary from interfering with others, Yomitan parses these stylesheets using regex and prefixes the styles with dictionary-level selectors. 

The current parser assumes that commas are only used in CSS to separate selectors. But valid CSS styles may also contain commas. As a result, some valid styles are mangled after being imported into Yomitan.

```css
/* Style for dictionary titled "my-dictionary-name" */
span[data-sc-name="my-green-text"] {
    color: color-mix(in srgb, lime, var(--text-color, var(--fg, #333)));
}
```

The above style is converted to this:

```css
[data-dictionary="my-dictionary-name"] span[data-sc-name="my-green-text"] {
[data-dictionary="my-dictionary-name"]     color: color-mix(in srgb,[data-dictionary="my-dictionary-name"]  lime,[data-dictionary="my-dictionary-name"]  var(--text-color,[data-dictionary="my-dictionary-name"]  var(--fg, #333)));
}
```

I think I see the responsible logic in at least two places in the codebase.

https://github.com/yomidevs/yomitan/blob/51f17d069596efc4c09377c51448b45fed3d4010/ext/js/display/display.js#L1255-L1263

https://github.com/yomidevs/yomitan/blob/51f17d069596efc4c09377c51448b45fed3d4010/ext/js/data/anki-note-data-creator.js#L609-L613
