### ISSUE TITLE
Add option to toggle off furigana in the example senstences

### ISSUE THREAD

**Issue by igalvidator** [yomidevs/yomitan#1663]
(Describe the feature or change)
As the title implies, I am humbly requesting for the ability to toggle off the furigana presented above the example sentences featured in the Jitendex.org dictionary.

**Comment by Casheeew** [comment]
You can probably achieve this with CSS using something like the :hover property

**Comment by igalvidator** [comment]
Can you possibly guide me as to how to do it? I have no coding exp, but I can follow instructions.

**Comment by Casheeew** [comment]
I will try to write a script later tomorrow

**Comment by igalvidator** [comment]
Than you and happy new year.

**Comment by Casheeew** [comment]
Sorry for the wait

You can use this CSS:

```css
.gloss-sc-rt {
    visibility: hidden;
}

.gloss-sc-ruby:hover .gloss-sc-rt {
    visibility: visible;
}

.gloss-sc-ruby:hover ~ .gloss-sc-ruby .gloss-sc-rt {
    visibility: visible;
}
```
