### ISSUE TITLE
Audio failed X is cut off on search page

### ISSUE THREAD

**Issue by Kuuuube** [yomidevs/yomitan#1814]
**Description**
The X is only halfway there. Example:
![Image](https://github.com/user-attachments/assets/16c876cf-2ece-4312-b9a2-ea714e1e9a5d)

This is caused by this css in `display.css`:
```css
.entry {
    content-visibility: auto;
}
```

Similar to #1738.

This same problem is seen in #1812 cutting off the selection indicator.
